#!/bin/bash
if [ $(docker image ls | grep wskstatus | wc -w | awk '{ print $1}') == "0" ] ; then docker build . -t wskstatus ; else echo "not building docker image" ; fi
docker run -it --rm -v $HOME/.wskprops:/root/.wskprops wskstatus swift run -c release wskstatus $@
